"""importacion patients addresses geocode_attempts

Revision ID: ca4dfdc05164
Revises: d67b2852712c
Create Date: 2026-08-29 22:31:12.138809
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'ca4dfdc05164'
down_revision: str | None = 'd67b2852712c'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mapping_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('counts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'validating', 'requires_correction', 'validated', 'geocoding', 'ready', 'failed', 'cancelled')", name='ck_import_batch_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_import_batches_org_period_hash_active', 'import_batches', ['organization_id', 'period', 'file_sha256'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    op.create_index('ix_import_batches_organization_id', 'import_batches', ['organization_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('display_ref', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_ref', name='uq_patients_org_ref')
    )
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('address_ciphertext', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('municipality', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=150), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('geocode_status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("geocode_status IN ('pending', 'matched', 'ambiguous', 'not_found', 'manual')", name='ck_address_geocode_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_addresses_active_per_patient', 'addresses', ['patient_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index('ix_addresses_organization_id', 'addresses', ['organization_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_json_encrypted', sa.Text(), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("validation_status IN ('pending', 'valid', 'invalid', 'corrected')", name='ck_import_row_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_import_rows_batch_row')
    )
    op.create_table('geocode_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_json_minimized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geocode_attempts_address_requested', 'geocode_attempts', ['address_id', sa.text('requested_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_geocode_attempts_address_requested', table_name='geocode_attempts')
    op.drop_table('geocode_attempts')
    op.drop_table('import_rows')
    op.drop_index('ix_addresses_organization_id', table_name='addresses')
    op.drop_index('uq_addresses_active_per_patient', table_name='addresses', postgresql_where=sa.text('is_active'))
    op.drop_table('addresses')
    op.drop_table('patients')
    op.drop_index('ix_import_batches_organization_id', table_name='import_batches')
    op.drop_index('uq_import_batches_org_period_hash_active', table_name='import_batches', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_table('import_batches')
    # ### end Alembic commands ###
